# Resource pack configuration
# Leave this as it is if you just want to play with the default settings
resource-pack:
  # URL of the resource pack
  url: "https://raw.githubusercontent.com/cometcake575/InfectionIsland/main/Resource%20Pack.zip"
  # Whether to force players to use the pack
  enforce: true
  # Message displayed to players when joining
  message: "Accept the resource pack to join the server"

# Number of lives each player currently has
lives: {}
